# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "personal-board"

[default.build]
[default.build.parameters]
cached = true
parallel = true

[default.validate]
[default.validate.parameters]
lint = true

[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
s3_prefix = "personal-board"
region = "us-east-1"
image_repositories = []
parameter_overrides = [
  "HostedZoneId=ZB9TUA073B5SH",
  "DomainName=board.seibtribe.us",
  "Environment=production",
  "StackName=personal-board"
]

[pbod]
[pbod.global]
[pbod.global.parameters]
stack_name = "personal-board-pbod"

[pbod.build]
[pbod.build.parameters]
cached = true
parallel = true

[pbod.validate]
[pbod.validate.parameters]
lint = true

[pbod.deploy]
[pbod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
s3_prefix = "personal-board-pbod"
region = "us-east-1"
image_repositories = []
parameter_overrides = [
  "HostedZoneId=ZB9TUA073B5SH",
  "DomainName=pbod.seibtribe.us",
  "Environment=pbod",
  "StackName=personal-board-pbod"
]