# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "personal-board"

[default.build]
[default.build.parameters]
cached = true
parallel = true

[default.validate]
[default.validate.parameters]
lint = true

[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
s3_prefix = "personal-board"
region = "us-east-1"
image_repositories = []
parameter_overrides = [
  "HostedZoneId=${HOSTED_ZONE_ID}",
  "DomainName=board.seibtribe.us",
  "Environment=production"
]